apiVersion: v2
name: wordpress-chart
description: A Helm chart for deploying WordPress with MySQL on Kubernetes
type: application

version: 0.1.11

appVersion: "1.11"

keywords:
  - wordpress
  - mysql
  - kubernetes
  - helm

home: https://github.com/moziauddin/wpMysql-pvc-kubernetes

maintainers:
  - name: Aleem Ahmad




  # helm repo add prometheus-community https://prometheus-community.github.io/helm-charts