apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: wordpress
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/aleemahmad0508/wordpress-helm-chart.git
    targetRevision: master
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

      # kubectl port-forward svc/argocd-server -n argocd 8080:443
      # https://localhost:8080