apiVersion: monitoring.coreos.com/v1
kind: Probe

metadata:
  name: wordpress-probe
  namespace: monitoring
  labels:
    release: prometheus

spec:
  jobName: wordpress-blackbox

  interval: 30s

  module: http_2xx

  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

  targets:
    staticConfig:
      static:
        - http://wordpress.wordpress.svc.cluster.local