apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: wordpress
  namespace: monitoring

  labels:
    release: prometheus

spec:
  namespaceSelector:
    matchNames:
      - wordpress

  selector:
    matchLabels:
      app: wordpress

  endpoints:
    - port: metrics
      interval: 30s
      path: /probe