apiVersion: v1
kind: Service

metadata:
  name: wordpress

  labels:
    app: wordpress


spec:

  type: {{ .Values.wordpress.service.type }}

  selector:
    app: wordpress
    tier: frontend


  ports:

    # WordPress website traffic
    - name: http
      port: {{ .Values.wordpress.service.port }}
      targetPort: 80



---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.storage.size }}

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: wordpress

  labels:
    app: wordpress


spec:

  replicas: {{ .Values.wordpress.replicaCount }}


  selector:

    matchLabels:
      app: wordpress
      tier: frontend


  strategy:

    type: Recreate


  template:

    metadata:

      labels:
        app: wordpress
        tier: frontend


    spec:

      serviceAccountName: wordpress-sa


      containers:


      # -----------------------
      # WordPress Container
      # -----------------------

      - name: wordpress

        image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"


        resources:

          requests:

            cpu: {{ .Values.wordpress.resources.requests.cpu }}

            memory: {{ .Values.wordpress.resources.requests.memory }}


          limits:

            cpu: {{ .Values.wordpress.resources.limits.cpu }}

            memory: {{ .Values.wordpress.resources.limits.memory }}


        env:

        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql


        - name: WORDPRESS_DB_NAME
          value: {{ .Values.mysql.database }}


        - name: WORDPRESS_DB_USER
          value: {{ .Values.mysql.username }}


        - name: WORDPRESS_DB_PASSWORD

          valueFrom:

            secretKeyRef:

              name: mysql-pass

              key: password



        ports:

        - name: http

          containerPort: 80



        volumeMounts:

        - name: wordpress-storage

          mountPath: /var/www/html



      

        


      volumes:

      - name: wordpress-storage

        persistentVolumeClaim:

          claimName: wp-pv-claim
# kubectl port-forward svc/argocd-server -n argocd 8080:443