name: Publish Helm Chart

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout master branch
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      # Package Helm Chart
      - name: Package Chart
        run: |
          mkdir -p .cr-release-packages
          helm package . --destination .cr-release-packages

      # Save package temporarily
      - name: Save Chart Package
        run: |
          mkdir -p /tmp/chart
          cp .cr-release-packages/*.tgz /tmp/chart/

      # Switch to gh-pages
      - name: Checkout gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      # Copy package to charts directory
      - name: Copy Chart
        run: |
          mkdir -p charts
          cp /tmp/chart/*.tgz charts/

      # Generate Helm repository index
      - name: Generate index.yaml
        run: |
          helm repo index . \
            --url https://aleemahmad0508.github.io/wordpress-helm-chart/charts

      # Commit and Push
      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "Update Helm Repository"

          git push origin gh-pages