name: Publish Helm Chart

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout master
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      # Package chart
      - name: Package Chart
        run: |
          mkdir -p package
          helm package . --destination package

      # Checkout gh-pages into another folder
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # Copy chart
      - name: Copy Chart
        run: |
          mkdir -p gh-pages/charts
          cp package/*.tgz gh-pages/charts/

      # Generate index.yaml
      - name: Generate Index
        run: |
          cd gh-pages
          helm repo index . \
            --url https://aleemahmad0508.github.io/wordpress-helm-chart/charts

      # Commit & Push
      - name: Commit Changes
        run: |
          cd gh-pages

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Update Helm Repository"
            git push origin gh-pages
          fi